#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/beans/XPropertySet.idl>

module com { module github { module jferard { module lopolyfill {

    // https://wiki.documentfoundation.org/ReleaseNotes/24.8#New_functions
    // FILTER function was added. (Balázs Varga, allotropia) tdf#126573 OASIS OFFICE-4156
    // LET function was added. (Balázs Varga, allotropia) tdf#137543
    // RANDARRAY function was added. (Balázs Varga, allotropia) tdf#126573
    // SEQUENCE function was added. (Balázs Varga, allotropia) tdf#126573
    // SORT function was added. (Balázs Varga, allotropia) tdf#126573 OASIS OFFICE-4157
    // SORTBY function was added. (Balázs Varga, allotropia) tdf#126573 OASIS OFFICE-4158
    // UNIQUE function was added. (Balázs Varga, allotropia) tdf#126573
    // XLOOKUP function was added. (Winfried Donkers) (Balázs Varga, allotropia) tdf#127293 OASIS OFFICE-4154
    // XMATCH function was added. (Balázs Varga, allotropia) tdf#128425 OASIS OFFICE-4155
    interface XLoPolyfill
    {
        // FILTER https://help.libreoffice.org/master/en-US/text/scalc/01/func_filter.html
        sequence< sequence< any > > lopFilter(
            [in] sequence< sequence< any > > inRange,
            [in] sequence< sequence< any > > criteria,
            [in] any defaultValue
            ) raises( com::sun::star::lang::IllegalArgumentException );

        // RANDARRAY https://help.libreoffice.org/master/en-US/text/scalc/01/func_randarray.html
        sequence< sequence< any > > lopRandarray(
            [in] any rows,
            [in] any columns,
            [in] any minValue,
            [in] any maxValue,
            [in] any integers
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // SEQUENCE https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_sequence.html
        sequence< sequence< any > > lopSequence(
            [in] long rows,
            [in] long columns,
            [in] any start,
            [in] any step
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // SORT https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_sort.html
        sequence< sequence< any > > lopSort(
            [in] com::sun::star::beans::XPropertySet oDoc,
            [in] sequence< sequence< any > > inRange,
            [in] any sortIndex,
            [in] any sortOrder,
            [in] any byCol
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // SORTBY https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_sortby.html
        sequence< sequence< any > > lopSortBy(
            [in] com::sun::star::beans::XPropertySet oDoc,
            [in] sequence< sequence< any > > inRange,
            [in] sequence< sequence< any > > sortByRange1,
            [in] long sortOrder1,
            [in] any sortByRange2,
            [in] any sortOrder2,
            [in] any sortByRange3,
            [in] any sortOrder3,
            [in] any sortByRange4,
            [in] any sortOrder4,
            [in] any sortByRange5,
            [in] any sortOrder5,
            [in] any sortByRange6,
            [in] any sortOrder6,
            [in] any sortByRange7,
            [in] any sortOrder7,
            [in] any sortByRange8,
            [in] any sortOrder8,
            [in] any sortByRange9,
            [in] any sortOrder9,
            [in] any sortByRange10,
            [in] any sortOrder10,
            [in] any sortByRange11,
            [in] any sortOrder11,
            [in] any sortByRange12,
            [in] any sortOrder12,
            [in] any sortByRange13,
            [in] any sortOrder13,
            [in] any sortByRange14,
            [in] any sortOrder14,
            [in] any sortByRange15,
            [in] any sortOrder15
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // UNIQUE https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_unique.html
        sequence< sequence< any > > lopUnique(
            [in] sequence< sequence< any > > inRange,
            [in] any byCol,
            [in] any uniqueness
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // XLOOKUP https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_xlookup.html
        sequence< sequence< any > > lopXLookup(
            [in] com::sun::star::beans::XPropertySet oDoc,
            [in] any criterion,
            [in] sequence< sequence< any > > searchRange,
            [in] sequence< sequence< any > > resultRange,
            [in] any defaultValue,
            [in] any matchMode,
            [in] any searchMode
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // XMATCH https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_xmatch.html
        long lopXMatch(
            [in] com::sun::star::beans::XPropertySet oDoc,
            [in] any criterion,
            [in] sequence< sequence< any > > searchRange,
            [in] any matchMode,
            [in] any searchMode
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // CHOOSECOLS https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_choosecols.html
        sequence< sequence< any > > lopChooseCols(
            [in] sequence< sequence< any > > array,
            [in] long column1,
            [in] any column2,
            [in] any column3,
            [in] any column4,
            [in] any column5,
            [in] any column6,
            [in] any column7,
            [in] any column8,
            [in] any column9,
            [in] any column10,
            [in] any column11,
            [in] any column12,
            [in] any column13,
            [in] any column14,
            [in] any column15,
            [in] any column16,
            [in] any column17,
            [in] any column18,
            [in] any column19,
            [in] any column20,
            [in] any column21,
            [in] any column22,
            [in] any column23,
            [in] any column24,
            [in] any column25,
            [in] any column26,
            [in] any column27,
            [in] any column28,
            [in] any column29,
            [in] any column30
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // CHOOSEROWS https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_chooserows.html
        sequence< sequence< any > > lopChooseRows(
            [in] sequence< sequence< any > > array,
            [in] long row1,
            [in] any row2,
            [in] any row3,
            [in] any row4,
            [in] any row5,
            [in] any row6,
            [in] any row7,
            [in] any row8,
            [in] any row9,
            [in] any row10,
            [in] any row11,
            [in] any row12,
            [in] any row13,
            [in] any row14,
            [in] any row15,
            [in] any row16,
            [in] any row17,
            [in] any row18,
            [in] any row19,
            [in] any row20,
            [in] any row21,
            [in] any row22,
            [in] any row23,
            [in] any row24,
            [in] any row25,
            [in] any row26,
            [in] any row27,
            [in] any row28,
            [in] any row29,
            [in] any row30
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // DROP https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_drop.html
        sequence< sequence< any > > lopDrop(
            [in] sequence< sequence< any > > array,
            [in] any rows,
            [in] any columns
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // TAKE https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_take.html
        sequence< sequence< any > > lopTake(
            [in] sequence< sequence< any > > array,
            [in] any rows,
            [in] any columns
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // EXPAND https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_expand.html
        sequence< sequence< any > > lopExpand(
            [in] sequence< sequence< any > > array,
            [in] any rows,
            [in] any columns,
            [in] any padWith
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // HSTACK https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_hstack.html
        sequence< sequence< any > > lopHStack(
            [in] sequence< sequence< any > > array,
            [in] any array1,
            [in] any array2,
            [in] any array3,
            [in] any array4,
            [in] any array5,
            [in] any array6,
            [in] any array7,
            [in] any array8,
            [in] any array9,
            [in] any array10,
            [in] any array11,
            [in] any array12,
            [in] any array13,
            [in] any array14,
            [in] any array15,
            [in] any array16,
            [in] any array17,
            [in] any array18,
            [in] any array19,
            [in] any array20,
            [in] any array21,
            [in] any array22,
            [in] any array23,
            [in] any array24,
            [in] any array25,
            [in] any array26,
            [in] any array27,
            [in] any array28,
            [in] any array29,
            [in] any array30
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // VSTACK https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_vstack.html
        sequence< sequence< any > > lopVStack(
            [in] sequence< sequence< any > > array,
            [in] any array1,
            [in] any array2,
            [in] any array3,
            [in] any array4,
            [in] any array5,
            [in] any array6,
            [in] any array7,
            [in] any array8,
            [in] any array9,
            [in] any array10,
            [in] any array11,
            [in] any array12,
            [in] any array13,
            [in] any array14,
            [in] any array15,
            [in] any array16,
            [in] any array17,
            [in] any array18,
            [in] any array19,
            [in] any array20,
            [in] any array21,
            [in] any array22,
            [in] any array23,
            [in] any array24,
            [in] any array25,
            [in] any array26,
            [in] any array27,
            [in] any array28,
            [in] any array29,
            [in] any array30
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // TOCOL https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_tocol.html
        sequence< sequence< any > > lopToCol(
            [in] sequence< sequence< any > > array,
            [in] any ignore,
            [in] any byColumn
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // TOROW https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_torow.html
        sequence< sequence< any > > lopToRow(
            [in] sequence< sequence< any > > array,
            [in] any ignore,
            [in] any byColumn
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // WRAPCOLS https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_wrapcols.html
        sequence< sequence< any > > lopWrapCols(
            [in] sequence< sequence< any > > inRange,
            [in] long wrapCount,
            [in] any padWith
        ) raises( com::sun::star::lang::IllegalArgumentException );

        // WRAPROWS https://help.libreoffice.org/25.8/en-US/text/scalc/01/func_wraprows.html
        sequence< sequence< any > > lopWrapRows(
            [in] sequence< sequence< any > > inRange,
            [in] long wrapCount,
            [in] any padWith
        ) raises( com::sun::star::lang::IllegalArgumentException );
    };

}; }; }; };